/*
 * This file is generated by jOOQ.
 */
package com.revolut.moneytransfer.persistence.jooq.tables;


import com.revolut.moneytransfer.enums.TransactionStatus;
import com.revolut.moneytransfer.enums.TransactionType;
import com.revolut.moneytransfer.persistence.jooq.Indexes;
import com.revolut.moneytransfer.persistence.jooq.Keys;
import com.revolut.moneytransfer.persistence.jooq.Public;
import com.revolut.moneytransfer.persistence.jooq.tables.records.TransactionRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transaction extends TableImpl<TransactionRecord> {

    private static final long serialVersionUID = -1636979762;

    /**
     * The reference instance of <code>PUBLIC.TRANSACTION</code>
     */
    public static final Transaction TRANSACTION = new Transaction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransactionRecord> getRecordType() {
        return TransactionRecord.class;
    }

    /**
     * The column <code>PUBLIC.TRANSACTION.UUID</code>.
     */
    public final TableField<TransactionRecord, UUID> UUID = createField(DSL.name("UUID"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.TRANSACTION.FROM_ACCOUNT_ID</code>.
     */
    public final TableField<TransactionRecord, UUID> FROM_ACCOUNT_ID = createField(DSL.name("FROM_ACCOUNT_ID"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>PUBLIC.TRANSACTION.TO_ACCOUNT_ID</code>.
     */
    public final TableField<TransactionRecord, UUID> TO_ACCOUNT_ID = createField(DSL.name("TO_ACCOUNT_ID"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.TRANSACTION.AMOUNT</code>.
     */
    public final TableField<TransactionRecord, Long> AMOUNT = createField(DSL.name("AMOUNT"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.TRANSACTION.STATUS</code>.
     */
    public final TableField<TransactionRecord, TransactionStatus> STATUS = createField(DSL.name("STATUS"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"PUBLIC\".\"TRANSACTION_STATUS\"").nullable(false), this, "", new org.jooq.impl.EnumConverter<java.lang.Object, com.revolut.moneytransfer.enums.TransactionStatus>(java.lang.Object.class, com.revolut.moneytransfer.enums.TransactionStatus.class));

    /**
     * The column <code>PUBLIC.TRANSACTION.TYPE</code>.
     */
    public final TableField<TransactionRecord, TransactionType> TYPE = createField(DSL.name("TYPE"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"PUBLIC\".\"TRANSACTION_TYPE\"").nullable(false), this, "", new org.jooq.impl.EnumConverter<java.lang.Object, com.revolut.moneytransfer.enums.TransactionType>(java.lang.Object.class, com.revolut.moneytransfer.enums.TransactionType.class));

    /**
     * Create a <code>PUBLIC.TRANSACTION</code> table reference
     */
    public Transaction() {
        this(DSL.name("TRANSACTION"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.TRANSACTION</code> table reference
     */
    public Transaction(String alias) {
        this(DSL.name(alias), TRANSACTION);
    }

    /**
     * Create an aliased <code>PUBLIC.TRANSACTION</code> table reference
     */
    public Transaction(Name alias) {
        this(alias, TRANSACTION);
    }

    private Transaction(Name alias, Table<TransactionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Transaction(Name alias, Table<TransactionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Transaction(Table<O> child, ForeignKey<O, TransactionRecord> key) {
        super(child, key, TRANSACTION);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FK_FROM_ACCOUNT_ID_INDEX_F, Indexes.FK_TO_ACCOUNT_ID_INDEX_F, Indexes.PRIMARY_KEY_F);
    }

    @Override
    public UniqueKey<TransactionRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_F;
    }

    @Override
    public List<UniqueKey<TransactionRecord>> getKeys() {
        return Arrays.<UniqueKey<TransactionRecord>>asList(Keys.CONSTRAINT_F);
    }

    @Override
    public List<ForeignKey<TransactionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TransactionRecord, ?>>asList(Keys.FK_FROM_ACCOUNT_ID, Keys.FK_TO_ACCOUNT_ID);
    }

    public Account fkFromAccountId() {
        return new Account(this, Keys.FK_FROM_ACCOUNT_ID);
    }

    public Account fkToAccountId() {
        return new Account(this, Keys.FK_TO_ACCOUNT_ID);
    }

    @Override
    public Transaction as(String alias) {
        return new Transaction(DSL.name(alias), this);
    }

    @Override
    public Transaction as(Name alias) {
        return new Transaction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(String name) {
        return new Transaction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(Name name) {
        return new Transaction(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, UUID, Long, TransactionStatus, TransactionType> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
