/*
 * This file is generated by jOOQ.
 */
package com.revolut.moneytransfer.persistence.jooq.tables.records;


import com.revolut.moneytransfer.persistence.jooq.tables.Ledger;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LedgerRecord extends UpdatableRecordImpl<LedgerRecord> implements Record3<UUID, UUID, Long> {

    private static final long serialVersionUID = -1618984056;

    /**
     * Setter for <code>PUBLIC.LEDGER.UUID</code>.
     */
    public LedgerRecord setUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.LEDGER.UUID</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>PUBLIC.LEDGER.ACCOUNT_ID</code>.
     */
    public LedgerRecord setAccountId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.LEDGER.ACCOUNT_ID</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>PUBLIC.LEDGER.AMOUNT</code>.
     */
    public LedgerRecord setAmount(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.LEDGER.AMOUNT</code>.
     */
    public Long getAmount() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Ledger.LEDGER.UUID;
    }

    @Override
    public Field<UUID> field2() {
        return Ledger.LEDGER.ACCOUNT_ID;
    }

    @Override
    public Field<Long> field3() {
        return Ledger.LEDGER.AMOUNT;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public UUID component2() {
        return getAccountId();
    }

    @Override
    public Long component3() {
        return getAmount();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public UUID value2() {
        return getAccountId();
    }

    @Override
    public Long value3() {
        return getAmount();
    }

    @Override
    public LedgerRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public LedgerRecord value2(UUID value) {
        setAccountId(value);
        return this;
    }

    @Override
    public LedgerRecord value3(Long value) {
        setAmount(value);
        return this;
    }

    @Override
    public LedgerRecord values(UUID value1, UUID value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LedgerRecord
     */
    public LedgerRecord() {
        super(Ledger.LEDGER);
    }

    /**
     * Create a detached, initialised LedgerRecord
     */
    public LedgerRecord(UUID uuid, UUID accountId, Long amount) {
        super(Ledger.LEDGER);

        set(0, uuid);
        set(1, accountId);
        set(2, amount);
    }
}
