/*
 * This file is generated by jOOQ.
 */
package com.revolut.moneytransfer.persistence.jooq;


import com.revolut.moneytransfer.persistence.jooq.tables.Account;
import com.revolut.moneytransfer.persistence.jooq.tables.Ledger;
import com.revolut.moneytransfer.persistence.jooq.tables.Transaction;
import com.revolut.moneytransfer.persistence.jooq.tables.records.AccountRecord;
import com.revolut.moneytransfer.persistence.jooq.tables.records.LedgerRecord;
import com.revolut.moneytransfer.persistence.jooq.tables.records.TransactionRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
    public static final UniqueKey<LedgerRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<TransactionRecord> CONSTRAINT_F = UniqueKeys0.CONSTRAINT_F;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LedgerRecord, AccountRecord> FK_LEDGER_ACCOUNT_ID = ForeignKeys0.FK_LEDGER_ACCOUNT_ID;
    public static final ForeignKey<TransactionRecord, AccountRecord> FK_FROM_ACCOUNT_ID = ForeignKeys0.FK_FROM_ACCOUNT_ID;
    public static final ForeignKey<TransactionRecord, AccountRecord> FK_TO_ACCOUNT_ID = ForeignKeys0.FK_TO_ACCOUNT_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> CONSTRAINT_E = Internal.createUniqueKey(Account.ACCOUNT, "CONSTRAINT_E", Account.ACCOUNT.UUID);
        public static final UniqueKey<LedgerRecord> CONSTRAINT_8 = Internal.createUniqueKey(Ledger.LEDGER, "CONSTRAINT_8", Ledger.LEDGER.UUID);
        public static final UniqueKey<TransactionRecord> CONSTRAINT_F = Internal.createUniqueKey(Transaction.TRANSACTION, "CONSTRAINT_F", Transaction.TRANSACTION.UUID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<LedgerRecord, AccountRecord> FK_LEDGER_ACCOUNT_ID = Internal.createForeignKey(com.revolut.moneytransfer.persistence.jooq.Keys.CONSTRAINT_E, Ledger.LEDGER, "FK_LEDGER_ACCOUNT_ID", Ledger.LEDGER.ACCOUNT_ID);
        public static final ForeignKey<TransactionRecord, AccountRecord> FK_FROM_ACCOUNT_ID = Internal.createForeignKey(com.revolut.moneytransfer.persistence.jooq.Keys.CONSTRAINT_E, Transaction.TRANSACTION, "FK_FROM_ACCOUNT_ID", Transaction.TRANSACTION.FROM_ACCOUNT_ID);
        public static final ForeignKey<TransactionRecord, AccountRecord> FK_TO_ACCOUNT_ID = Internal.createForeignKey(com.revolut.moneytransfer.persistence.jooq.Keys.CONSTRAINT_E, Transaction.TRANSACTION, "FK_TO_ACCOUNT_ID", Transaction.TRANSACTION.TO_ACCOUNT_ID);
    }
}
