/*
 * This file is generated by jOOQ.
 */
package com.revolut.moneytransfer.persistence.jooq;


import com.revolut.moneytransfer.persistence.jooq.tables.Account;
import com.revolut.moneytransfer.persistence.jooq.tables.Ledger;
import com.revolut.moneytransfer.persistence.jooq.tables.Transaction;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>PUBLIC.LEDGER</code>.
     */
    public static final Ledger LEDGER = Ledger.LEDGER;

    /**
     * The table <code>PUBLIC.TRANSACTION</code>.
     */
    public static final Transaction TRANSACTION = Transaction.TRANSACTION;
}
